### ISSUE TITLE
Zip Recruiter Qns

### ISSUE THREAD

**Issue by sahilbhende25** [perixtar/2024-Tech-OA#54]
Hello, the qns on zip recruiter have same source image, I know its not an issue but if you have them please can you upload their respective photos, I wanted to gauge the constraints. If at all they got covered in any of the photos of their corresponding qns

**Comment by tomtoto757** [comment]
Okie! Will handle it! Thanks for pointing out!

**Comment by tomtoto757** [comment]
> Hello, the qns on zip recruiter have same source image, I know its not an issue but if you have them please can you upload their respective photos, I wanted to gauge the constraints. If at all they got covered in any of the photos of their corresponding qns

Aloha! I just fixed Zip Recruiter source image issue. It will take a little while to let the updates show up on your end. Feel free to let me know if you have any other questions or concerns! I am always here ready to help :D

**Comment by sahilbhende25** [comment]
You guys are gems! Kudos and shoutout to your efforts. Its working for me. Thanks
