### ISSUE TITLE
TikTok OA

### ISSUE THREAD

**Issue by sahilbhende25** [perixtar/2024-Tech-OA#63]
Hello Team,

The TikTok OA apparently had SQL and MCQ qns too, any chance you have those qns. Also I'd love to connect with contributors, any way we can connect on any social media. Thanks a ton for all your efforts!

**Comment by tomtoto757** [comment]
> Hello Team,
> 
> The TikTok OA apparently had SQL and MCQ qns too, any chance you have those qns. Also I'd love to connect with contributors, any way we can connect on any social media. Thanks a ton for all your efforts!

Hi sahillbhende25! 

The team is on the Discord server. Feel free to join the server and meet us!

**Comment by tomtoto757** [comment]
> Hello Team,
> 
> The TikTok OA apparently had SQL and MCQ qns too, any chance you have those qns. Also I'd love to connect with contributors, any way we can connect on any social media. Thanks a ton for all your efforts!

The discord invite link is on 2024 tech oa page
