### ISSUE TITLE
Amazon OA Dropped Requests 🪻

### ISSUE THREAD

**Issue by zhehengluoK** [perixtar/2024-Tech-OA#64]
The 2nd example included one more 6. The list should be [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7] with in total three six in it.

**Comment by tomtoto757** [comment]
> The 2nd example included one more 6. The list should be [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7] with in total three six in it.

Hi zheheng! 

Thank you so much for pointing out! I have edited the input. The update should show up on your end soon! If you have any other questions/concerns, pls feel free to let me know! Happy coding!

**Comment by perixtar** [comment]
Thanks @zhehengluoK . I think for both input, the output should be 2.If there is extra 6, then that 6 will be dropped and all the 7 will not get dropped. But great job for catching the bug!
