### ISSUE TITLE
Meta Questions

### ISSUE THREAD

**Issue by sahilbhende25** [perixtar/2024-Tech-OA#65]
Hello Team,

I am not able to open questions related to Meta company, the error popping up is 404, page not found. Please can you fix it asap.

Regards,
SSB

**Comment by FastPrepIO** [comment]
Thanks for let us know. We are fixing it now.

**Comment by tomtoto757** [comment]
> Hello Team,
> 
> I am not able to open questions related to Meta company, the error popping up is 404, page not found. Please can you fix it asap.
> 
> Regards, SSB

Hello SSB! 

Meta is up again :) 

Regards,
tomtato

**Comment by sahilbhende25** [comment]
Thanks Tomtato,

Regards,
Tomato

**Comment by tomtoto757** [comment]
> Thanks Tomtato,
> 
> Regards, Tomato

You are welcome SSB :)

**Comment by sahilbhende25** [comment]
Bro I was just messing with you XD, its all love for you!

Also dude I just posted a solution for one of the question (Meta). It seems If I reopen the solution, the counter increases for views. Shouldn't that just be for unique views that the solution gets or is the implementation different in backend.

**Comment by tomtoto757** [comment]
Thank you SSB so much for posting the solution! It is due to the implementation different in backend XD. All can be modified in the future.

**Comment by sahilbhende25** [comment]
No worries!
