### ISSUE TITLE
Needs improvement in solution section 

### ISSUE THREAD

**Issue by vedant-z** [perixtar/2024-Tech-OA#66]
While creating solution post on practice platform, if someone leaves the "Title" field blank and click on "Create" button then it throws popup that "Title can't be blank" but the content of post is lost. So one needs to create the post again with all the content lost.

**Comment by perixtar** [comment]
Hi Vedant,

Thanks for your suggestion! We will working on fixing it!

**Comment by vedant-z** [comment]
@perixtar Seems like the issue is resolved. Is there any way I can contribute on issues like this? I am really interested :D

**Comment by perixtar** [comment]
Hi Vedant, thanks for your support! If you would like to contribute to any problems, feel free to join the discord and share any OA problems you found. Our community members would highly appreciate that! We currently don't look for anyone to contribute to the code but definitely stay tuned.
