### ISSUE TITLE
Possible questions for veeva

### ISSUE THREAD

**Issue by sahilbhende25** [perixtar/2024-Tech-OA#67]
Hey Team,

I recently explored about this company called Veeva and they are hiring for freshers. Any chance you have info about their OA? Any help would do because I have one in coming days.

Regards,
SSB

**Comment by tomtoto757** [comment]
> Hey Team,
> 
> I recently explored about this company called Veeva and they are hiring for freshers. Any chance you have info about their OA? Any help would do because I have one in coming days.
> 
> Regards, SSB

Hi SSB, 

We currently do not have info for Veeva. Once we do, we will include them.

Regards,
Tomtato

**Comment by sahilbhende25** [comment]
Thanks!

**Comment by sahilbhende25** [comment]
Guys I have an emergency, If possible please could you get any information about Veeva questions it would be of great help, they are actively hiring!

**Comment by tomtoto757** [comment]
> Guys I have an emergency, If possible please could you get any information about Veeva questions it would be of great help, they are actively hiring!

Hi SSB! 

I only found 1 from early 2023. Not sure if it will help or not. If you'd still take a look, feel free to join the server and dm tomtato :) GL!

**Comment by sahilbhende25** [comment]
Cool, I'll dm. Thanks a ton bro!
