### ISSUE TITLE
BlackRock OA 2025

### ISSUE THREAD

**Issue by sahilbhende25** [perixtar/2024-Tech-OA#70]
Hey guys, blackrock has internship OA for summer 2025. Any chance you have received those qns. If you receive them, please could you post it on our repo.

**Comment by tomtoto757** [comment]
> Hey guys, blackrock has internship OA for summer 2025. Any chance you have received those qns. If you receive them, please could you post it on our repo.

Hello! 

Of course! I’ll definitely keep an eye out for them and post them in our repo if I receive them :)

**Comment by sahilbhende25** [comment]
cool!

**Comment by tomtoto757** [comment]
> cool!

Surprise!! I found a few of them :P

**Comment by tomtoto757** [comment]
> > cool!
> 
> Surprise!! I found a few of them :P

I found two. One is not that complete, so I would't add it to the collection. Feel free to dm me through the discord serva so I can send it to you.

**Comment by abena07** [comment]
what is your discord ? @ZikGroot
