### ISSUE TITLE
extra " in some link

### ISSUE THREAD

**Issue by xl1393** [perixtar/2024-Tech-OA#73]
Some latest entries have an extra " at the end of the fastprep link, causing 404 error. Example:

| Cisco | [Find Mean and Mode](https://www.fastprep.io/problems/cisco-find-mean-and-mode") | <a href="https://www.fastprep.io/problems/cisco-find-mean-and-mode"><img src="https://i.imgur.com/ojP4tYR.png" width="118" alt="Pratice"/> </a> | August, 30, 2024 |
| Cisco | [Count Number with Sum of Digits](https://www.fastprep.io/problems/cisco-count-numbers-with-sum-of-digits") | <a href="https://www.fastprep.io/problems/cisco-count-numbers-with-sum-of-digits"><img src="https://i.imgur.com/ojP4tYR.png" width="118" alt="Pratice"/> </a> | August, 30, 2024 |
| Cisco | [Calculate Mean and Mode](https://www.fastprep.io/problems/cisco-calculate-mean-and-mode") | <a href="https://www.fastprep.io/problems/cisco-calculate-mean-and-mode"><img src="https://i.imgur.com/ojP4tYR.png" width="118" alt="Pratice"/> </a> | August, 30, 2024 |
| Cisco | [Find Words in Grid](https://www.fastprep.io/problems/cisco-find-words-in-grid") | <a href="https://www.fastprep.io/problems/cisco-find-words-in-grid"><img src="https://i.imgur.com/ojP4tYR.png" width="118" alt="Pratice"/> </a> | August, 30, 2024 |

**Comment by tomtoto757** [comment]
Hello! The extra " has been taken away. They should be good to go now. Thank you for pointing out the error :)

**Comment by xl1393** [comment]
Yes it is working now, you can close the issue. Thanks!
